project-2-the-force/theLanguageEmporium/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

theLanguageEmporium/force-app/main/default/objects/Course__c/fields/Course_ID__c.field-meta.xml
<CustomField>
    <fullName>Course_ID__c</fullName>
    <displayFormat>CID-{0000}</displayFormat>
    <label>Course ID</label>
    <type>AutoNumber</type>
</CustomField>

theLanguageEmporium/force-app/main/default/classes/ContactData.cls
public with sharing class ContactData {
    
    @AuraEnabled
    public static user fetchUser(){
     // query current user information  
      User oUser = [select id,Country,Email,FirstName,LastName FROM User Where id =: userInfo.getUserId()];
        return oUser;
    }
}
   

/*@AuraEnabled
    public static list<Course__c> getCourseList(Id recordId)
    {
        List<Course__c> Courselist = [Select Course_ID__c, name FROM Course__c];
        return Courselist;
    } */