project-2-the-force/theLanguageEmporium/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

theLanguageEmporium/force-app/main/default/objects/Lesson__c/Lesson__c.object-meta.xml
<CustomObject>
    <label>Lesson</label>
    <nameField>
        <label>Lesson Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lessons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

project-2-the-force/theLanguageEmporium/force-app/main/default/objects/Lesson__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

theLanguageEmporium/force-app/main/default/objects/Quiz_Data__c/Quiz_Data__c.object-meta.xml
<CustomObject>
    <label>Quiz Data</label>
    <nameField>
        <displayFormat>QUIZ-{0000}</displayFormat>
        <label>Quiz Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

project-2-the-force/theLanguageEmporium/force-app/main/default/objects/Quiz_Data__c/fields/Learner__c.field-meta.xml
<CustomField>
    <fullName>Learner__c</fullName>
    <label>Learner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quiz Data</relationshipLabel>
    <relationshipName>Quiz_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

theLanguageEmporium/force-app/main/default/classes/CourseContentController.cls
public with sharing class CourseContentController {

    @AuraEnabled
    public static List<Lesson__c> getLessons(String courseId, String learnerId){
        try {
            List<Lesson__c> lessons = New List<Lesson__c>([SELECT id, name FROM Lesson__c WHERE course__c = :courseId]);
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Quiz_Data__c> methodName(String courseId, String learnerId){
        try {
            List<Quiz_Data__c> lessons = New List<Quiz_Data__c>([SELECT id, name FROM Quiz_Data__c WHERE course__c = :courseId AND Learner__c = :learderId]);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}