project-2-the-force/theLanguageEmporium/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

theLanguageEmporium/force-app/main/default/objects/Course__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dev_Team</valueSetName>
    </valueSet>
</CustomField>

project-2-the-force/theLanguageEmporium/force-app/main/default/objects/Order/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

project-2-the-force/theLanguageEmporium/force-app/main/default/objects/Order/fields/Learner__c.field-meta.xml
<CustomField>
    <fullName>Learner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Learner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

theLanguageEmporium/force-app/main/default/globalValueSets/Dev_Team.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>Esperanto</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>German</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <customValue>
        <fullName>Mandarin</fullName>
    </customValue>
    <customValue>
        <fullName>Romanian</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Swedish</fullName>
    </customValue>
    <masterLabel>Language(s)</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

theLanguageEmporium/force-app/main/default/classes/StorePageController.cls
//Abdulloh Y
//Apex Controller for functionality in the Store Component

public class StorePageController {
    
    //Method to get the available courses with relevant fields from the database.
    @AuraEnabled
        public static List<Course__c> getCourseList(){
            try {
            List<Course__c> courseList = [SELECT Id, Name, Start_Date__c, Language__c FROM Course__c];
            return courseList;
            } catch (Exception e) {
                throw new AuraHandledException(e.getMessage());
            }
        }

    //Method to insert orders with the courses that were in the shopping cart.
    @AuraEnabled
    public static void createAndInsertOrders(List<Course__c> courseList){
        try {
            List<Order> orders = new List<Order>();
            for(Course__c crs: courseList){
                Order order = new order();
                //order.Course__c = crs.id;
                //order.Learner__c = crs.???
            }
            insert orders;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    }